### ISSUE TITLE
Component File Structure - Card

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/Tom_Thomas_7_through_9#15]
In order to keep your file structure a bit cleaner, I would recommend nesting smaller components inside the component they pertain to. This might be a more logical way to navigate a codebase with hundreds of components.

For example, I would recommend moving CardBanner, CardContent, and Card Image into the Card folder.

**Comment by thomas-galligan** [comment]
Thanks Kristina, we have added this to the next PR
