### ISSUE TITLE
mock content is currently stored in the Content Component 

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/Tom_Thomas_7_through_9#18]
Your mock content is not a Component and so it might be cleaner to store that outside of the Content Component.

Also, as your content component is what renders the main content of your page (outside header and footer), I would recommend wrapping it in a ```main``` tag (instead of a Fragment).

**Comment by thomas-galligan** [comment]
Our mock content is now stored in separate files :)
