### ISSUE TITLE
fallback image if no card image  available?

### ISSUE THREAD

**Issue by joaoviana** [FACxBeamery/Tom_Thomas_7_through_9#32]
<img width="214" alt="Screenshot 2019-11-01 at 10 40 46" src="https://user-images.githubusercontent.com/7611706/68019601-28b7bc00-fc94-11e9-9c1a-e52df5a6750b.png">

There's plenty of ways for doing this, but try to do some conditional rendering on this. 

if no image -> return fallbackImage (this fallback image could be specific for each type of media source. a blue bird for tweets, a newspaper icon etc etc)

if image -> well, just use it

**Comment by thomas-galligan** [comment]
We do have a fallback image available, but currently it's conditional on an image URL existing, rather than the image actually rendering properly (which is harder to test for). We're working on this!
