### ISSUE TITLE
another component?

### ISSUE THREAD

**Issue by joaoviana** [FACxBeamery/Tom_Thomas_7_through_9#34]
https://github.com/FACxBeamery/Tom_Thomas_7_through_9/blob/49ec62f18c0918dc390f0280e22d5cd6d9dcb820/src/components/Header/Header.js#L26-L40

maybe you could render iteratively 3 divs?

**Comment by thomas-galligan** [comment]
We could have made this into an element but it seemed excessive (since it's just a line).
