### ISSUE TITLE
Integration testing 🧬

### ISSUE THREAD

**Issue by joaoviana** [FACxBeamery/Tom_Thomas_7_through_9#35]
I see great opportunities for integration tests here! 
- When you tap on the 'heart', it turns red, "favouritisation" complete!!
- Clicking on the burger menu shows me the filters container!

**Comment by joaoviana** [comment]
have seen just now the testing for the burger menu! sorry 😁

**Comment by thomas-galligan** [comment]
Thanks for the suggestion, we do indeed have testing on our burger menu which covers the vast majority of our codebase.
